# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "អំពីខ្ញុំ"
  url = "#about"
  weight = 20

[[main]]
  name = "អត្ថបទខ្លីៗ"
  url = "#posts"
  weight = 30

[[main]]
  name = "បោះពុម្ព"
  url = "#publications"
  weight = 40

[[main]]
  name = "បទបង្ហាញ"
  url = "#talks"
  weight = 50
  
[[main]]
  name = "កិច្ចការបង្រៀន"
  url = "#teachings"
  weight = 60 

[[main]]
  name = "Life in Mexico"
  url = "life-in-mexico/"
  weight = 70
  
[[main]]
  name = "កម្រងរូបភាព"
  url = "#gallery"
  weight = 80
[[main]]
  name = "ទំនាក់ទំនង"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
